class Univers:
    def __init__(self, name):
        self.id = None
        self.name = name
        self.description = None

    def to_map(self):
        return {
            'id': self.id,
            'name': self.name,
            #'description': self.description
        }

    @classmethod
    def from_map(cls, map):
        universe = cls(map.get('name', ''))
        universe.id = map.get('id')
        universe.description = map.get('description')

        return universe

    def generate_description(self):
        # Générer avec OpenAI
        self.description = f"Description de l'univers {self.name} générée par OpenAI"













""" 
class Univers:
    def __init__(self, name):
        self.id = None
        self.name = name
        self.description = None

    def to_map(self):
        return {
            'id': self.id,
            'name': self.name,
            # 'description': self.description
        }

    @staticmethod
    def from_map(map):
        universe = Univers(map['name'])
        universe.id = map['id']
        universe.description = map['description']

        return universe

    def generate_description(self):
        # Generate with OpenAI
        self.description = f"Description of the universe {self.name} generated by OpenAI"
 """